name: base
channels:
  - defaults
dependencies:
  - conda
  - python=3.9
  - conda-env
  - conda-build
  - conda-verify
  - _ipyw_jlab_nb_ext_conf
  - anaconda-navigator==2.3.2
  - navigator-updater
  - pandas
  - numpy
  - matplotlib
  - seaborn
  - statsmodels
  - geopandas
  - shapely
  - requests
  - pyproj
  - geopy
